### PR TITLE
Add edited_message event

### PR DESCRIPTION
**Pull request by chris54721**
See https://github.com/yagop/node-telegram-bot-api/pull/191

### CODE REVIEW

**Comment by GochoMugo** [comment]
Nice. No need to draft the PR here. Our bot (@themedusabot) does it for us :sunglasses:! Otherwise, thanks alot!

**Comment by chris54721** [comment]
Okay, just wanted to make sure you could merge it right away 😉

**Comment by kamikazechaser** [comment]
Nice!

**Comment by GochoMugo** [comment]
@Chris54721 Again Thanks! You are among the few people that contribute code back to an open-source project.

**Comment by chris54721** [comment]
@GochoMugo Did you publish the update to npm? It looks like `node-telegram-bot-api-latest@0.2.0` still has the old files in `lib/`.

**Comment by GochoMugo** [comment]
Ooh! My bad! I had **not** noticed I was **not** building the files. Just fixed that. The changes should be available in **v0.2.1**.

**Pull request merged**
