### PR TITLE
sendDocument with fileOpts test

### PR DESCRIPTION
**Pull request by themedusabot**
---

Original-PR: https://github.com/yagop/node-telegram-bot-api/pull/152
Author: evolun

---

/ghupfork by Forfuture LLC (http://medusa.forfuture.co.ke)

### CODE REVIEW

**Comment by GochoMugo** [comment]
@kamikazechaser you okay with this? Can we swap a simpler doc?

**Comment by kamikazechaser** [comment]
Yeah!

**Comment by GochoMugo** [comment]
Are you able to open the file?

**Comment by kamikazechaser** [comment]
We have to run our own travis test to confirm!

**Comment by GochoMugo** [comment]
@kamikazechaser you want to set it up?

**Comment by kamikazechaser** [comment]
sawa...will do it!

**Comment by GochoMugo** [comment]
We are deprecating this repository, as the original repository is now up-to-date. We will be waiting for you there. :smile:

**Pull request closed without merging**
