### PR TITLE
Implement 'leaveChat'

### PR DESCRIPTION
**Pull request by themedusabot**
API Method [leaveChat](https://core.telegram.org/bots/api#leavechat): https://core.telegram.org/bots/api#leavechat

---

Original-PR: https://github.com/yagop/node-telegram-bot-api/pull/186
Author: GochoMugo

---

/ghupfork by Forfuture LLC (http://medusa.forfuture.co.ke)

### CODE REVIEW

**Comment by kamikazechaser** [comment]
Could this packaged be pushed to npm as v.0.0.3

**Comment by GochoMugo** [comment]
@kamikazechaser Should we bump minor version or patch version?

IMO I would think the version should now be v0.1.0

**Comment by kamikazechaser** [comment]
Sawa

**Comment by GochoMugo** [comment]
@kamikazechaser It is done! v0.1.0 out!

**Pull request merged**
